excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://aaronmyhre.github.io
title: Who will watch the cats?
tagline: Aaron and Maya leave SF, hijinks ensue
description: This is something maya needs to do. 
paginate: 5